bitirmeSon/urls.py
# from django.conf.urls import url
from atexit import register
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import data.views


urlpatterns = [
    path("", data.views.index, name="index"),
    path("admin/", admin.site.urls),
    path("login/", data.views.login, name="login"),
    path("register/", data.views.register, name="register"),
    path("about/", data.views.about, name="about"),

    path("galeri/", data.views.galeri ,name='galeri'), # galeri sayfası için
    path("yorum/", data.views.yorum ,name='yorum'), # yorum
    path("data/", include("data.urls", namespace='data'),name="data-index"),
    path("blog/", include("blog.urls", namespace='blog'),name="blog-index"),
    path("gallery/", include("gallery.urls", namespace='gallery'),name="gallery-index"),
    path("twitterdata/", include("twitterdata.urls", namespace='twitterdata'),name="twitterdata-index"),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path

from .views import index

app_name = "blog"


urlpatterns = [
    path("", index, name="index"),
    # path("export_csv", export_csv, name="export-csv"),
    # path("export_pdf", export_pdf, name="export-pdf"),
    # path("blog", blog, name="blog"),
]

data/urls.py
from django.urls import path

from .views import chart_select_view, export_csv, export_pdf

app_name = "data"


urlpatterns = [
    path("", chart_select_view, name="main-data"),
    path("export_csv", export_csv, name="export-csv"),
    path("export_pdf", export_pdf, name="export-pdf"),
    
]

gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.index, name="index"),
    #path("gallery", views.gallery),
    
    
    
]

blog/models.py
import django
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify

# Create your models here.
DEFAULT = "twiter"
CATEGORY = (
    ("twitter", "Twitter"),
    ("instagram", "Instagram"),
    ("facebook", "Facebook"),
)


class Post(models.Model):
    user = models.ForeignKey("auth.User", related_name="post",
                             on_delete=models.CASCADE, verbose_name="Kullanıcı")
    title = models.CharField(max_length=120, verbose_name="Başlık")
    content = models.TextField(verbose_name="İçerik")
    publish_date = models.DateTimeField(
        verbose_name="Yayın Tarihi", auto_now_add=True)
    image = models.ImageField(null=True, blank=True,
                              upload_to="uploads", verbose_name="Resim")
    slug = models.SlugField(unique=True, editable=False, max_length=130)
    grup = models.CharField(choices=CATEGORY, max_length=15,
                            default=DEFAULT, verbose_name="Kategori")

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("")

    def get_unique_slug(self):
        slug = slugify(self.title.replace("ı", "i"))
        unique_slug = slug
        counter = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, counter)
            counter += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        return super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-publish_date", "id"]

data/models.py
from django.db import models
from django.db.models.fields import CharField
from django.contrib.auth.models import User

# Create your models here.
# user = settings.AUTH_USER_MODEL


class girdi(models.Model):
    tarih = models.DateField()
    bugunkuVaka = models.PositiveIntegerField()
    bugunkuHasta = models.PositiveIntegerField()
    bugunkuTest = models.PositiveIntegerField()
    bugunkuVefat = models.PositiveIntegerField()
    bugunkuIyilesen = models.PositiveIntegerField()
    agirHasta = models.PositiveIntegerField()

    def __str__(self):
        return str(self.tarih) + " tarihli girdiler"


    # for i in User.objects.all():
    #     if i:
    #         print(i.id, i.username, i.is_authenticated)
    # kullanici = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)


class ozelGunler(models.Model):
    tarih = models.DateField()
    ozelGunTuru = CharField(max_length=200)
    aciklama = CharField(max_length=500)

    def __str__(self):
        return str(self.tarih) + " tarihli özel gün"


# class user(models.Model):
#     userName = models.CharField()

# hastalardaZaturreOrani,
# toplamTest,
# toplamVaka,
# toplamVefat,
# toplamIyilesenHasta,

twitterdata/models.py
from django.db import models

# Create your models here.

    
  

blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from blog.models import Post
from .utils import get_client_ip
# Create your views here.


def index(request):
    context ={
        "title": "Blog",
        "client_ip": get_client_ip(request),
        "posts": Post.objects.all()
    }
    return render(request, "blog.html", context)

data/views.py
from django.http.response import HttpResponse
from django.template.loader import get_template
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from xhtml2pdf import pisa
import pandas as pd
import numpy as np
import json
import csv
from datetime import datetime

from .utils import get_simple_plot, get_client_ip

# Create your views here.


def export_csv(request):
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = (
        "attachment; filename=covIData-" + str(datetime.now()) + ".csv"
    )
    response["encoding"] = "utf-8"
    writer = csv.writer(response)
    writer.writerow(
        [
            "tarih",
            "bugunkuVaka",
            "bugunkuTest",
            "bugunkuVefat",
            "bugunkuIyilesen",
        ]
    )  # Türkçe karakter sorunu mevcut
    for item in df2.values:
        writer.writerow(
            [
                item[0],
                item[1],
                item[3],
                item[4],
                item[5],
            ]
        )
    # CSV indirme işlemleri
    return response


def export_pdf(request):
    template_path = "export_pdf.html"
    json_records = df2.reset_index().to_json(orient="records")
    data = []
    data = json.loads(json_records)

    toplam_veri = {  # df['MyColumn'].sum()
        "tVaka": df2["bugunkuVaka"].sum(),
        "tTest": df2["bugunkuTest"].sum(),
        "tVefat": df2["bugunkuVefat"].sum(),
        "tIyilesen": df2["bugunkuIyilesen"].sum(),
    }
    context = {
        "baslik": "Covid19 Veri Özeti",
        "data": data,
        "graph": graph,
        "sumOfdata": toplam_veri,
    }
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        "filename=covIDRapor-" + str(datetime.now()) + ".pdf"
    )  # attachment;
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse("Bazı sorunlar meydana geldi <pre>" + html + "</pre>")
    return response


def index(request):
    with open("userLog.log", "a") as file_object:
        file_object.write(
            "\nKullanıcı IP : "
            + get_client_ip(request)
            + "\tGiriş Saati : "
            + str(datetime.now())
        )
    context = {
        "title": "Ana Sayfa",
        "client_ip": get_client_ip(request),
    }
    return render(request, "main.html", context)


def login(request):
    context = {
        "title": "Login",

    }
    return render(request, "login.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()

    context = {
        "title": "Register",
        "form": form
    }
    return render(request, "register.html", context)


def about(request):
    context = {
        "title": "About",
    }
    return render(request, "about.html", context)

def country(request):
    context = {
        "title": "Ülke Bazında Veriler",
        
    }
    return render(request, "countries.html", context)
def galeri(request):
    context = {
        "title": "Galeri",
        "client_ip": get_client_ip(request),
    }
    return render(request, "galeri.html", context)

def yorum(request):
    context = {
        "title": "Analiz",
        "client_ip": get_client_ip(request),
    }
    return render(request, "yorum.html", context)

def chart_select_view(request):
    global graph
    graph = None
    error_msg = None
    df = None
    global df2
    df2 = None
    covid19 = pd.read_csv(
        "data3.csv",
        parse_dates=True,
    )  # index_col="tarih"
    df = (
        covid19.copy()
        .rename({"tarih": "Tarih"}, axis=1)
        .drop(
            {
               #"hastalardaZaturreOrani",
                "toplamTest",
                #"toplamVaka",
                "toplamVefat",

                "toplamIyilesenHasta",
            },
            axis=1,
        )
    )
    df2 = df.copy()

    if df.shape[0] > 0:

        if request.method == "POST":
            chart_type = request.POST.get("grafik_turu")
            date_from = request.POST["date_from"]
            date_to = request.POST["date_to"]

            # df['Tarih'] = df['Tarih'].apply(lambda x: x.strftime("%d-%m-%Y"))
            df = df.astype({"Tarih": np.datetime64})
            df["Tarih"] = df["Tarih"].dt.strftime("%Y-%m-%d")
            # gunluk = df.loc[df["Tarih"].isin(["27-06-2021", "29-06-2021"])]
            df2 = df[(df["Tarih"] >= date_from) & (df["Tarih"] <= date_to)]
            if chart_type != "":
                if date_from != "" and date_to != "":
                    df2 = df[(df["Tarih"] >= date_from)
                             & (df["Tarih"] <= date_to)]
                    # print(datetime.datetime.strftime(date_from)
                    df2 = df2.astype({"Tarih": np.datetime64})
                    df2["Tarih"] = df2["Tarih"].dt.strftime("%d/%m/%Y")
                    # print(df2["Tarih"](0))
                    # print(datetime.strptime(date_from, '%m-%d-%Y').date())
                    title = date_from + " ile " + date_to + " arasındaki " + chart_type

                    # print(type(df2))
                    graph = get_simple_plot(
                        chart_type,
                        title,
                        x=df2["Tarih"],
                        y=df2["bugunkuVaka"],
                        data=df2,
                    )
                else:
                    error_msg = "trh"  # Tarih alanları boş
            else:
                error_msg = "grf"  # Grafik türü seçilmedi
    else:
        error_msg = "kyt"  # Kayıt yok
    # print(df2)
    json_records = df2.reset_index().to_json(orient="records")
    data = []
    data = json.loads(json_records)

    template_name = "data.html"
    toplam_veri = {  # df['MyColumn'].sum()
        "tVaka": df2["bugunkuVaka"].sum(),
        "tTest": df2["bugunkuTest"].sum(),
        "tVefat": df2["bugunkuVefat"].sum(),
        "tIyilesen": df2["bugunkuIyilesen"].sum(),
        "tAgirHasta": df2["agirHasta"].sum(),
        #"tZature": df2["hastalardaZaturreOrani"].mean(),
        
    }
    ortalama_veri = {  
        "OVaka": round(df2["bugunkuVaka"].mean(),2),
        "OTest": round(df2["bugunkuTest"].mean(),2),
        "OVefat": round(df2["bugunkuVefat"].mean(),2),
        "OIyilesen": round(df2["bugunkuIyilesen"].mean(),2),
        "OAgirHasta": round(df2["agirHasta"].mean(),2),
        "OZature": round(df2["hastalardaZaturreOrani"].mean(),2),
        
    }
    context = {
        "title": "Data Sayfası",
        "hata_msj": error_msg,
        "graph": graph,
        "data": data,
        "sumOfdata": toplam_veri,
        "meanOfdata": ortalama_veri,
        "client_ip": get_client_ip(request),
    }
    return render(request, template_name=template_name, context=context)

    # print(
    #     gunluk.rename(
    #         {
    #             "bugunkuVaka": "Vaka",
    #             "bugunkuHasta": "Hasta",
    #             "bugunkuTest": "Test",
    #             "bugunkuVefat": "Vefat",
    #             "bugunkuIyilesen": "İyileşen",
    #         },
    #         axis=1,
    #     )
    # )

gallery/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from blog.models import Post
from .utils import get_client_ip
def gallery(request):
    return render(request, "gallery.html")


def index(request):
    context = {
        "title": "Galeri",
        "posts": Post.objects.all(),
        "client_ip": get_client_ip(request),
    }
    return render(request, "gallery.html", context)

twitterdata/views.py
from django.shortcuts import render
from .utils import get_client_ip
# Create your views here.

import pandas as pd
import numpy as np
import json
import csv
from datetime import datetime
#

import plotly.express as px
from django.shortcuts import render
from plotly.offline import plot
import plotly.graph_objs as p
import plotly.express as px

   


def index(request):
    df=pd.read_csv( "analiz_edilmis.csv") #veriden yazı vs sil öyle ayıklık olar kyap
    x=df['date']
    y=df["nlikes"]  
    df1=pd.read_csv( "analiz_edilmis_gun.csv")
    a=df1['Gun']
    b=df1["Tweets_Skoru"]  
    plot_div = plot([p.Scatter(x=a, y=b,
                        mode='lines', name='test',
                        opacity=0.8, marker_color='green')],
               output_type='div')
    #bar_div=plot(px.line(df, x=x, y=df.columns, title='Günlere Göre Atılan Tweet Sayısı'),output_type='div')
    fig=px.line(df1,x=a, y=df1.columns, title='2021 Kasım Ayı Günlere Göre Tweet İstatistiği',width=1300,height=530)
    fig.update_layout( paper_bgcolor='#d6d6d6')
    line_div=plot(fig,output_type='div')
    
      
    
    return render(request, "twitterdata.html", context={'plot_div': line_div,"client_ip": get_client_ip(request),"title": "Twitter Grafik Veri"})




#def index(request):
  #  context = {
  #      "title": "Twitter Verileri",
       
  #      "client_ip": get_client_ip(request),
  #  }
  #  return render(request, "twitterdata.html", context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock title %}

{% block content %}

<div class="ui container">
    <div class="ui container">
        <div class="ui huge header">Hakkımızda</div>
    </div>
    
</div>

 
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="tr-TR">
  <head>
    <!-- Required meta tags -->
    <meta http-equiv="content-language" content="tr-TR">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initialscale=1, shrink-to-fit=no"/>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <!-- JQuery min js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
    <!-- semantic css & js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
    <!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
    
    
    <title>{% block title %} {% endblock title %} | Covid19</title>
  </head>
<style>
  body{
    background-color: rgb(214,214,214); 
  }
</style>
  <body>
    
    {% include 'navbar.html' %}
    <br>
      {% block content %} 
    
      {% endblock content %}
    
    
    {% include 'footer.html' %}
    <script src="{% static 'static_project/main.js' %}"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script> <!-- ploty kütüphanesinin hzılı yüklemesi için için   -->

    <script>
    $(document).ready(function(){
      $("a").hover(function(){
        $(this).css("background-color", "#C58342");
        }, function(){
        $(this).css("background-color", "#d6d6d6");
      });
    });
      
    </script>
  </body>
  
</html>

templates/countries.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock title %}

{% block content %}

<div class="ui container">
    <div class="ui container">
        <div class="ui huge header">Ülkeler</div>
    </div>
    
</div>

 
{% endblock content %}

templates/data.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{title}} {% endblock title %}

{% block content %}

<style>.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
  }</style>

<div class="ui container">
    <h1 class="ui huge header">Data Ana Sayfası</h1>
    <div>
        {% if hata_msj %}
            <div class="ui red message medium">
                Lütfen formu eksiksiz doldurunuz.
            </div>
        {% else %}
            <div class="ui green message medium">
                Belirli tarih aralığında Covid19 verilerine ulaşmak için seçin yapınız. Ardından verileri listelemek için <strong><em>Verileri Getir</em></strong>
                butonuna basınız. Grafik türü seçmediğiniz takdirde sadece veriler listelenecektir. Verileri listeledikten sonra <strong>CSV, Excel</strong>
                ve <strong>PDF</strong> formatında indirme yapabilirsiniz.
            </div>
        {% endif %}
        <br>
        <form action="" method="POST" class="ui form">
            {% csrf_token %}
            
            <div class="two fields">
                <div class="field">
                    <label>Başlangış tarihi:</label>
                    <input type="date" name="date_from" placeholder="ilk tarih" value="2020-03-11">
                    
                </div>
                <div class="field">
                    <label>Bitiş tarihi:</label>
                    <input type="date" name="date_to" placeholder="Son tarih" value="2021-07-05">
                </div>
            </div>
            <div class="two fields">
                <div class="field">
                    <label>Grafik Şekli :</label>
                    <div class="ui selection dropdown">
                        <input type="hidden" name="grafik_turu">
                        <i class="dropdown icon"></i>
                        <div class="default text">---------</div>
                        <div class="menu">
                            <div class="item" value="bar">Bar grafik</div>
                            <div class="item" value="line">Çizgi grafik</div>
                            <div class="item" value="count">Sayım grafiği</div>
                        </div>
                    </div>
                </div>
                
                <div class="field">
                    <label>&nbsp;</label>
                    <button class="ui primary button" type="submit">Verileri Getir</button>
                    
                    
                    {% if request.POST %}{% if data %}
                        <a class="ui button secondary" href="{% url 'data:export-csv'  %}" target="_self"> 
                            <i aria-hidden="true" class="download icon"></i>&nbsp;CSV indir</a> 
                        
                        <a class="ui button positive" href="{% url 'data:export-pdf'  %}" target="_blank">
                            <i aria-hidden="true" class="download icon"></i>&nbsp;PDF indir</a>
                    {% endif %}{% endif %}
                </div>
                
            </div>

           
        </form>
        <img src="{% static 'images/grafik5.png' %}" style="width:90%", class="center">

        {% if request.POST %}
            {% if graph %}
            <img src="data:image/png;base64, {{ graph | safe }}" alt="" srcset="">
            {% endif %}
            {% if data %}
            

            <table class="ui compact celled inverted teal large table">
                <thead>
                  <tr>
                    <th>Tarih</th>
                    <th>Bugunkü Vaka</th>
                    <th>Bugunkü Test</th>
                    <th>Bugunkü Vefat</th>
                    <th>Bugunkü İyileşen</th>
                    <th>Ağır Hasta</th>
                    <th>Zatürre Oranı(%)</th>
                    <th>Sokağa Çıkma Yasağı</th>
                    <th>Tüm Ülke</th>
                  </tr>
                </thead>
                <tbody>
                {% for i in data %}
                <tr>
                  <td class="center aligned">{{i.Tarih}}</td>
                  <td>{{i.bugunkuVaka}}</td>
                  <td>{{i.bugunkuTest}}</td>
                  <td>{{i.bugunkuVefat}}</td>
                  <td>{{i.bugunkuIyilesen}}</td>
                  <td>{{i.agirHasta}}</td>
                  <td>{{i.hastalardaZaturreOrani}}</td>
                  <td>{{i.sokagaCikmaYasagi}}</td>
                  <td>{{i.tumUlke}}</td>
                  
                </tr>
                {% endfor %}

                </tbody>
                
                
                <tfoot>
                    <tr>
                        <th class="center aligned">Toplam</th>
                        <th>{{ sumOfdata.tVaka }}</th>
                        <th>{{ sumOfdata.tTest }}</th>
                        <th>{{ sumOfdata.tVefat }}</th>
                        <th>{{ sumOfdata.tIyilesen }}</th>
                        <th>{{ sumOfdata.tAgirHasta }}</th>
                        <th>None</th>
                        <th>None</th>
                        <th>None</th>
                    </tr>
                </tfoot>
                <tfoot>
                    <tr>
                        <th class="center aligned">Ortalma</th>
                        <th>{{ meanOfdata.OVaka }}</th>
                        <th>{{ meanOfdata.OTest }}</th>
                        <th>{{ meanOfdata.OVefat }}</th>
                        <th>{{ meanOfdata.OIyilesen }}</th>
                        <th>{{ meanOfdata.OAgirHasta }}</th>
                        <th>{{ meanOfdata.OZature }}</th>
                        <th>None</th>
                        <th>None</th>
                    </tr>
                </tfoot>
            </table>
            {% endif %}
        {% endif %}
        <br><br>
    </div>

</div>



{% endblock content %}

templates/footer.html
<!-- <div class="ui inverted vertical footer segment">
    <div class="ui container">
        Travel Match 2015. All Rights Reserved
    </div>
</div> -->

<!-- <div class="ui clearing segment">
    <h3 class="ui right floated header">
      Go Forward
    </h3>
    <h3 class="ui left floated header">
      Go Back
    </h3>
  </div> -->

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock title %}

{% block content %}

<div class="ui container">
    <div class="ui container">
        <div class="ui huge header">Üye Giriş Formu</div>
    </div>
    
</div>
 
{% endblock content %}

templates/main.html
{% extends 'base.html' %} 

{% block title %} {{title}} {% endblock title %} 

{% block content %}
<div class="ui container">
    <div class="ui huge header">Ana Sayfa</div>
</div>
<div class="ui container">
  
    <br><img class="ui fluid image" src="https://covid19.saglik.gov.tr/assets/images/covidhaftalik.png" alt="">
    <div class="overlay">
      <div class="text">Dünya geneline yayılan COVID-19 salgınının Türkiye'de tespit edilen ilk vakası Sağlık Bakanlığı 
          tarafından 11 Mart günü açıklandı. Ülkedeki virüse bağlı ilk ölüm ise 15 Mart 2020'de gerçekleşti. 
          Sağlık Bakanı Fahrettin Koca, 1 Nisan 2020'de yaptığı açıklamada koronavirüs vakalarının tüm Türkiye'ye yayıldığını açıkladı.
          15 Nisan 2022 itibarıyla Türkiye'de koronavirüs ile enfekte olmuş toplam hasta sayısının 14.987.583 olduğu ve mevcut hastalardan
          975 kişinin yoğun bakımda tedavi görmekte olduğu; şimdiye kadar iyileşen hasta sayısının 14.719.749 ve ölen hasta sayısının toplam 
          98.532 kişi olduğu bildirildi. Bugüne kadar toplam 156.868.643 test yapıldı. 14 Ocak 2021'de başlayan aşı uygulaması kapsamında 
          5 Mayıs 2021 itibarıyla toplam 24 milyon 278 bin 886 kişiye aşı yapıldı. Bunlardan 14 milyon 327 bin 674 kişiye birinci doz aşı 
          uygulanırken 9 milyon 951 bin 212 kişiye ise ikinci doz aşı uygulandı</div>
  </div>
    
</div>

<style>
    .container {
      position: relative;
      width: 50%;
    }
    
    .image {
      display: block;
      width: 100%;
      height: auto;
    }
    
    .overlay {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      height: 100%;
      width: 100%;
      opacity: 0;
      transition: .5s ease;
      background-color: #008CBA;
    }
    
    .container:hover .overlay {
      opacity: 1;
    }
    
    .text {
      color: white;
      font-size: 20px;
      position: absolute;
      top: 50%;
      left: 50%;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);
      text-align: center;
    }
    </style>
{% endblock content %}

templates/navbar.html
<div class="ui attached stackable menu" style="background-color: rgb(214,214,214)">
  <div class="ui container" >
    <a class=" item" href="{% url 'index'  %}">
      <i class="home icon" ></i> Ana Sayfa
    </a>
    <a class="item" href="{% url 'data:main-data'  %}">
      <i class="grid layout icon"></i> Data
    </a>

    <a class="item" href="{% url 'blog:index'  %}"> <i class="comment alternate icon"></i> Blog </a>
    <a class="item" href="{% url 'galeri'  %}"><i class="images icon"></i> Galeri </a>
    <!-- <a class="item" href="{% url 'yorum'  %}"><i class="file alternate icon"></i> Analiz </a> -->
    <a class="item" href="{% url 'gallery:index'  %}"><i class="image icon"></i> Albüm </a>
    <a class="item" href="{% url 'twitterdata:index'  %}"><i class="chart area icon"></i> Twitter Grafik Veri </a>
    <div class="ui simple dropdown item">
      Diğer
      <i class="dropdown icon" ></i>
      <div class="menu" style="background-color: rgb(207, 207, 207);">
        <a class="item" href="{% url 'register'  %}"><i class="signup icon"></i> Register</a>
        <a class="item" href="{% url 'login'  %}"><i class="user icon"></i> Login</a>
        <a class="item" onclick="alert('Veri giriş modülü henüz aktif değil.')"><i class="upload icon"></i> Veri Gir</a>
        <a class="item" href="{% url 'index'  %}admin"><i class="settings icon"></i> Admin</a>
        <a class="item" href="{% url 'about'  %}"><i class="globe icon"></i> Hakkımızda </a>
        
      </div>
    </div>
    <div class="right item">
      <form action="" method="post" class="ui small form">
        <div class="ui input" >
          {% if client_ip %}
          <p class="ui basic image label"  style="background-color: #C58342;">
            <img src="https://semantic-ui.com/images/avatar/small/elliot.jpg" alt="" />
            {{ client_ip }}
          </p>
          {% endif %}

          <!-- <input type="text" placeholder="Mail Listesi" size="5" />
          <input class="ui blue button" type="button" value="Abone Ol"> -->
        </div>
      </form>
    </div>
  </div>
</div>
